### ISSUE TITLE
Z-index when markers + virtual tour is enabled

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#1337]
### Describe the bug

When both Virtual Tour Plugin and Markers Plugins are enabled, the div of markers has a lower value for z-index than virtual tour arrows, making markers not hoverable/clickable. This is reproducible in default demo of Virtual Tour Plugin in docs.

Changing `.psv-markers` z-index to 12 solves the issue.

### Photo Sphere Viewer version

5.8.0

### Plugins loaded

VirtualTourPlugin, MarkersPlugin

### OS & browser

At least Firefox 127 under Linux

**Comment by PanierAvide** [comment]
Well the fix is more subtle, as both virtual tour arrows & markers div have a full width/height sizing, so whatever the z-index is, one make the other not clickable. I have a working solution with:

```css
.psv-markers { /* markers above + click events going through */
	z-index: 12 !important;
	pointer-events: none;
}
.psv-markers .psv-marker { /* restore clicks events on markers individually */
	pointer-events: initial;
}
```
