### ISSUE TITLE
Plan plugin maximize size limit

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1405]
### Describe the feature

As a user, I would like to be able to set a size limit to the maximized plan plugin so that it doesn't take up all the available screen space, instead being as tall and wide as the values set on these limits.  

### Alternatives you've considered

When listening for the `view-changed` event, I've tried to re-set the `plan`'s `height` and `width` with no success. 

```
const planPlugin = viewer.getPlugin<PlanPlugin>(PlanPlugin);
planPlugin.addEventListener('view-changed', (data) => {
    if (data.view === 'maximized') {
        planPlugin.setOptions({
            size: {
              height: '350px',
              width: '400px',
            },
        });
    } else if (data.view === 'normal') {
        // plan.setZoom(14);
    }
```

**Comment by mistic100** [comment]
Just do it in CSS

```css
.psv-plan--maximized {
 max-width: 400px;
 max-height: 350px;
}
```

**Comment by mistic100** [comment]
That's not a temporary fix, this is the only solution I would propose, I am not willing to add more options.

Anyway th above code can be improved

```css
.psv-plan--maximized {
  width: 500px !important;
  height: 500px !important;
}
.psv--has-navbar .psv-plan--maximized {
  height: 500px !important;
}

@container psv-container (max-width: 500px) {
  .psv-plan--maximized {
    width: 100% !important;
  }
}
```

It's a bit clunky because of the existing !important in the default stylesheet but it works.
