### ISSUE TITLE
Ability to change the default error svg in case when panorama cannot be loaded

### ISSUE THREAD

**Issue by ssneha1811** [mistic100/Photo-Sphere-Viewer#1555]
### Describe the feature

Want to have the ability to change the default error svg in case when panorama cannot be loaded.

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/df649098-2ad2-4775-be58-838f2fed91f7" />

**Comment by mistic100** [comment]
I do not plan to add such option. I think you can do it with some CSS override.

```css
.psv-overlay-image svg { display: none; }

psv-overlay-image { background-image: url(.....) };
```
