### ISSUE TITLE
changing loading circle color 

### ISSUE THREAD

**Issue by ix3bd2** [mistic100/Photo-Sphere-Viewer#557]
hi.
i want to change the loading circle color to something else. is this possible ?

**Comment by mistic100** [comment]
```css
.psv-loader {
  color: pink;
}
```
