### ISSUE TITLE
Styling marker SVG with CSS

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#736]
What's the best way to style SVG markers with CSS? Say adding a hover effect to a SVG marker? I tried in the example below but it's not working. 

I notice if I use the HTML version that is commented-out that it gets some default tilting behavior on hover which I assume is some kind of global style setting?

https://jsfiddle.net/xkenabdq/1/

**Comment by mistic100** [comment]
Well if you use valid CSS it works

your version :

```css
.goto: hover {
  fill: "rgba(200, 0, 0, 0.8)"
}
```

valid version :

```css
.goto:hover {
  fill: rgba(200, 0, 0, 0.8);
}
```
